In [34]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pandas as pd
from sklearn.model_selection import train_test_split

In [35]:
df1 = pd.DataFrame.from_csv("./data/Ejemplo12.csv", header=0)
df1

,Precion arterial,Azucar en la Sangre,Colesterol,Alergia Antibiotico,Otras Alergias,Administrar Farmaco
1,Alta,Alto,Alto,No,No,Si
2,Alta,Alto,Alto,Si,No,Si
3,Baja,Alto,Bajo,No,No,Si
4,Media,Alto,Alto,No,Si,No
5,Media,Bajo,Alto,Si,Si,No
6,Baja,Bajo,Alto,Si,Si,Si
7,Alta,Bajo,Alto,Si,No,Si
8,Alta,Bajo,Bajo,No,Si,Si
9,Alta,Alto,Bajo,Si,Si,No
10,Baja,Bajo,Alto,Si,Si,Si
11,Media,Bajo,Bajo,Si,Si,Si
12,Alta,Bajo,Alto,Si,Si,No
13,Baja,Alto,Alto,Si,Si,Si
14,Baja,Alto,Bajo,No,No,Si

In [36]:
# Conseguimos los features y targets de cada columna del DataFrame
tags = []
targets = []
features = []
for i in range(len(df1.columns) - 1):
    features.append(df1[df1.columns[i]].unique())
    tags.append(df1[df1.columns[i]].unique())
    print("Categoria {0}: {1} Valores: {2}".format(i, df1.columns[i], features[i]))

target = df1[df1.columns[-1]].unique()
tags.append(df1[df1.columns[-1]].unique())
print("Lista de Targets: {0}".format(target))

Categoria 0: Precion arterial Valores: ['Alta' 'Baja' 'Media']
Categoria 1: Azucar en la Sangre Valores: ['Alto' 'Bajo']
Categoria 2: Colesterol Valores: ['Alto' 'Bajo']
Categoria 3: Alergia Antibiotico Valores: ['No' 'Si']
Categoria 4: Otras Alergias Valores: ['No' 'Si']
Lista de Targets: ['Si' 'No']

In [37]:
def tag2numeric(tag, location):
    '''Convierte los tags del DataFrame a valores num√©ricos dependiedo del tag
    
    Args
    ------
    tag -- string con el nombre de la categoria
    location -- columna a la que pertenece el tag
    '''
    
    for i in range(len(tags[location])):
        if tag == tags[location][i]:
            return i

In [38]:
# Ejecutamos tag2numeric para pasar de variables categoricas a enteros.

for i in range(len(df1.columns)):
    df1[df1.columns[i]] = df1[df1.columns[i]].apply(lambda x: tag2numeric(x,i))

df1

,Precion arterial,Azucar en la Sangre,Colesterol,Alergia Antibiotico,Otras Alergias,Administrar Farmaco
1,0,0,0,0,0,0
2,0,0,0,1,0,0
3,1,0,1,0,0,0
4,2,0,0,0,1,1
5,2,1,0,1,1,1
6,1,1,0,1,1,0
7,0,1,0,1,0,0
8,0,1,1,0,1,0
9,0,0,1,1,1,1
10,1,1,0,1,1,0
11,2,1,1,1,1,0
12,0,1,0,1,1,1
13,1,0,0,1,1,0
14,1,0,1,0,0,0

In [39]:
# Separamos ambos en features y targets asi como training y test data
X_train, X_test, y_train, y_test = train_test_split(df1[df1.columns[:-1]], df1[df1.columns[-1]], test_size=0.2)

In [40]:
# Para entrenar con ID3 debemos especificar que el criterio a seguir es la entropia
clf = DecisionTreeClassifier(criterion="entropy")
clf = clf.fit(X_train,y_train)

In [41]:
prediccion = clf.predict(df1[df1.columns[:-1]])

In [42]:
df_predict = df1.assign(prediccion=prediccion)

In [43]:
df_predict

,Precion arterial,Azucar en la Sangre,Colesterol,Alergia Antibiotico,Otras Alergias,Administrar Farmaco,prediccion
1,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0
3,1,0,1,0,0,0,0
4,2,0,0,0,1,1,1
5,2,1,0,1,1,1,1
6,1,1,0,1,1,0,0
7,0,1,0,1,0,0,0
8,0,1,1,0,1,0,0
9,0,0,1,1,1,1,1
10,1,1,0,1,1,0,0
11,2,1,1,1,1,0,0
12,0,1,0,1,1,1,1
13,1,0,0,1,1,0,0
14,1,0,1,0,0,0,0

In [44]:
print("El score de nuestro algoritmo es: {0}%".format(clf.score(X_test,y_test)*100))

El score de nuestro algoritmo es: 100.0%